---
- hosts: vagrant
  sudo: yes
  gather_facts: no
  vars:
    name: deployer
    local_src_root: ../..
    build_root: /mnt/{{ name }}
    build: "{{ build_root }}/target/release/{{ name }}"

  roles:
    - base

  tasks:
    - name: source is syncronized
      synchronize: src={{ local_src_root }} dest={{ build_root }}

    - name: rust & cargo are installed
      shell: "curl -s https://static.rust-lang.org/rustup.sh | sudo sh"
      args:
        creates: /usr/local/bin/rustc

    - name: build is up-to-date
      shell: "cargo build --release"
      args:
        chdir: "{{ build_root }}"

    - name: put server into path
      command: /bin/cp {{ build }} /usr/local/bin/{{ name }}

    - name: copy build back to local machine
      synchronize: src={{ build }}
                   dest={{ local_src_root }}/{{ name }}.linux
                   mode=pull