---
- hosts: all
  sudo: yes
  gather_facts: no
  vars:
    name: deployer
    build_root: /mnt/{{ name }}
    build: "{{ build_root }}/target/release/{{ name }}"
  tasks:
  - name: ansible repo exists
    apt_repository: repo=ppa:ansible/ansible

  - name: ansible is installed
    apt: name=ansible

  - name: source is syncronized
    synchronize: src=../ dest={{ build_root }}

  - name: rust & cargo are installed
    shell: "curl -s https://static.rust-lang.org/rustup.sh | sudo sh"
    args:
      creates: /usr/local/bin/rustc

  - name: build is up-to-date
    shell: "cargo build --release"
    args:
      chdir: "{{ build_root }}"

  - name: put server into path
    command: /bin/cp {{ build }} /usr/local/bin/{{ name }}

  - name: copy build back to local machine
    synchronize: src={{ build }}
                 dest=../{{ name }}.linux
                 mode=pull